import Clio5 from "../images/book-car/clio5.png";
import Micra from "../images/book-car/nissan-micra.png";
import Stepway from "../images/book-car/stepway.png";
import C3 from "../images/book-car/c3.png";
import Peg208 from "../images/book-car/peg208.png";
import Corsa from "../images/book-car/corsa.png";
// import Clio4 from "../images/book-car/clio4.png";
// import Astra from "../images/book-car/astra.png";
// import Logan from "../images/book-car/logan.png";
// import Fiesta from "../images/book-car/fiesta.png";

export const CAR_DATA = [
  [
    {
      id: 1,
      name: "Clio 5",
      price: "37",
      img: Clio5,
      model: "Clio 5",
      mark: "Renault",
      year: "2023",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Petrol",
    },
  ],
  [
    {
      id: 2,
      name: "Nissan Micra 2023",
      price: "45",
      img: Micra,
      model: "Micra",
      mark: "Nissan",
      year: "2023",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Petrol",
    },
  ],
  [
    {
      id: 3,
      name: "Dacia Stepway 2019",
      price: "30",
      img: Stepway,
      model: "Stepway",
      mark: "Dacia",
      year: "2019",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Petrol",
    },
  ],
  [
    {
      id: 4,
      name: "Citroen C3 2022",
      price: "35",
      img: C3,
      model: "C3",
      mark: "Citroen",
      year: "2022",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Petrol",
    },
  ],
  [
    {
      id: 5,
      name: "Peugeot 208 2023",
      price: "50",
      img: Peg208,
      model: "208",
      mark: "Peugeot",
      year: "2023",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Petrol",
    },
  ],
  [
    {
      id: 6,
      name: "Opel Corsa 2024",
      price: "25",
      img: Corsa,
      model: "Corsa",
      mark: "Opel",
      year: "2024",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Petrol",
    },
  ],
  // [
  //   {
  //     id: 7,
  //     name: "Clio 4 2019",
  //     price: "28",
  //     img: Clio4,
  //     model: "Clio 4",
  //     mark: "Renault",
  //     year: "2019",
  //     doors: "4/5",
  //     air: "Yes",
  //     transmission: "Manual",
  //     fuel: "Petrol",
  //   },
  // ],
  // [
  //   {
  //     id: 8,
  //     name: "Opel Astra 2024",
  //     price: "40",
  //     img: Astra,
  //     model: "Astra",
  //     mark: "Opel",
  //     year: "2024",
  //     doors: "4/5",
  //     air: "Yes",
  //     transmission: "Manual",
  //     fuel: "Petrol",
  //   },
  // ],
  // [
  //   {
  //     id: 9,
  //     name: "Dacia Logan 2019",
  //     price: "22",
  //     img: Logan,
  //     model: "Logan",
  //     mark: "Dacia",
  //     year: "2019",
  //     doors: "4/5",
  //     air: "Yes",
  //     transmission: "Manual",
  //     fuel: "Petrol",
  //   },
  // ],
  // [
  //   {
  //     id: 10,
  //     name: "Clio 4 2019",
  //     price: "28",
  //     img: Clio4,
  //     model: "Clio 4",
  //     mark: "Renault",
  //     year: "2019",
  //     doors: "4/5",
  //     air: "Yes",
  //     transmission: "Manual",
  //     fuel: "Petrol",
  //   },
  // ],
  // [
  //   {
  //     id: 11,
  //     name: "Clio 5 2023",
  //     price: "37",
  //     img: Clio5,
  //     model: "Clio 5",
  //     mark: "Renault",
  //     year: "2023",
  //     doors: "4/5",
  //     air: "Yes",
  //     transmission: "Manual",
  //     fuel: "Petrol",
  //   },
  // ],
  // [
  //   {
  //     id: 12,
  //     name: "Ford Fiesta 2023",
  //     price: "35",
  //     img: Fiesta,
  //     model: "Fiesta",
  //     mark: "Ford",
  //     year: "2023",
  //     doors: "4/5",
  //     air: "Yes",
  //     transmission: "Manual",
  //     fuel: "Petrol",
  //   },
  // ],
  // [
  //   {
  //     id: 13,
  //     name: "Dacia Stepway 2024",
  //     price: "33",
  //     img: Stepway,
  //     model: "Stepway",
  //     mark: "Dacia",
  //     year: "2024",
  //     doors: "4/5",
  //     air: "Yes",
  //     transmission: "Manual",
  //     fuel: "Petrol",
  //   },
  // ],
];
